# Generated by Django 2.1.7 on 2019-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('d1', models.CharField(max_length=400)),
                ('d2', models.CharField(max_length=400)),
                ('d3', models.CharField(max_length=400)),
                ('votes', models.IntegerField()),
                ('image', models.TextField()),
            ],
        ),
    ]
