# Generated by Django 2.1.7 on 2019-03-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='options_model',
            name='url',
            field=models.TextField(default='https://www.flipkart.com/?affid=kazifarha'),
        ),
    ]
