# Generated by Django 2.1.7 on 2019-03-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Options', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options_model',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
