# Generated by Django 2.1.7 on 2019-03-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Options', '0002_auto_20190316_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options_model',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
