# Generated by Django 2.1.7 on 2019-03-16 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Options', '0003_auto_20190316_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='options_model',
            name='name',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='options_model',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Title.Title_model'),
        ),
    ]
