# Generated by Django 2.1.7 on 2019-03-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Title', '0001_initial'),
        ('Options', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voots_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Options.Options_model')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Title.Title_model')),
            ],
        ),
    ]
