# Generated by Django 2.1.7 on 2019-03-18 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Title', '0002_auto_20190318_0053'),
        ('Voots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voots_model',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Title.Title_model'),
            preserve_default=False,
        ),
    ]
