# Generated by Django 2.1.7 on 2019-03-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Options', '0001_initial'),
        ('Voots', '0002_voots_model_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='voots_model',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Options.Options_model'),
            preserve_default=False,
        ),
    ]
